# Config to define all available selections
# Selections contain object- and event-level cuts
# Previously defined selections can be imported with '<<' or '*'
# Any nested collections created by "<<" or '*' operations will be flattened in sidm_processor.py


# Cuts to apply to objects that are clustered into lepton jets
ljsource_cuts: &ljsource_cuts
  obj_cuts: &obj_ljsource_cuts
    electrons: 
      - "pT > 10 GeV"
      - "|eta| < 2.4"
      - "looseID"
    muons: 
      - "looseID"
      - "pT > 5 GeV"
      - "|eta| < 2.4"
    photons:
      - "pT > 20 GeV"
      - "|eta| < 2.5"
      - "looseID"
    dsaMuons: 
      - "pT > 10 GeV"
      - "|eta| < 2.4"
      - "ifcsczero"
      - "segOverlap < 0.66"
      - "extrapolatedDr > 0.2" 
      - "isSubsetAnyPFMuon False"
      - "normChi2 < 4"
      - "DT + CSC hits > 12"
      - "DT + CSC stations >= 2"
      - "ptErrorOverPT < 1"

# PV filter and cosmic veto
pvAndCosmic_cuts: &pvAndCosmic_cuts
  obj_cuts: &obj_pvAndCosmic_cuts
    pvs: 
      - "ndof > 4"
      - "|z| < 24 cm"
      - "|rho| < 0.2 mm"
  evt_cuts: &evt_pvAndCosmic_cuts
    - "PV filter"
    - "Cosmic veto"

baseNoLj: &baseNoLj
  <<: *pvAndCosmic_cuts
  obj_cuts: &obj_baseNoLj
    <<: *obj_ljsource_cuts
    <<: *obj_pvAndCosmic_cuts
  evt_cuts: &evt_baseNoLj
    - *evt_pvAndCosmic_cuts

base: &base
  obj_cuts: &obj_base
    <<: *obj_baseNoLj
  lj_cuts: &lj_base
    - "pT > 30 GeV"
    - "|eta| < 2.4"
  evt_cuts: &evt_base
    - *evt_baseNoLj
    - ">=2 LJs"
    
4mu: &4mu
  <<: *base
  evt_cuts: &evt_4mu
    - *evt_base
    - "4mu"

2mu2e: &2mu2e
  <<: *base
  evt_cuts: &evt_2mu2e
    - *evt_base
    - "2mu2e"

# basic analysis selections with LJ-A dR matching
matchedLj: &matchedLj
  obj_cuts: &obj_matchedLj
    <<: *obj_base
  lj_cuts: 
    - *lj_base
    - "dR(LJ, A) < 0.2"
  evt_cuts: &evt_matchedLj
    - *evt_base
    - ">=2 matched As"

4mu_matchedLj: &4mu_matchedLj
  <<: *matchedLj
  evt_cuts: &evt_4mu_matchedLj
    - *evt_matchedLj
    - "4mu"

2mu2e_matchedLj: &2mu2e_matchedLj
  <<: *matchedLj
  evt_cuts: &evt_2mu2e_matchedLj
    - *evt_matchedLj
    - "2mu2e"

# basic selections with cuts on A properties and no LJ cuts
baseNoLj_promptA: &baseNoLj_promptA
  <<: *baseNoLj
  obj_cuts:
    <<: *obj_baseNoLj
    genAs:
      - "lxy < 10 cm"

baseNoLj_displacedA: &baseNoLj_displacedA
  <<: *baseNoLj
  obj_cuts:
    <<: *obj_baseNoLj
    genAs:
      - "10 cm <= lxy < 100 cm"

baseNoLj_veryDisplacedA: &baseNoLj_veryDisplacedA
  <<: *baseNoLj
  obj_cuts:
    <<: *obj_baseNoLj
    genAs:
      - "lxy >= 100 cm"
      
#Selections for electrons only
##All reco electrons in the barrel
barrelE: &barrelE
  evt_cuts: 
    - "Keep all evts"
  obj_cuts: &obj_barrelE
    electrons: 
      - "|eta| < 1.479"
 
##All reco electrons in the endcaps
endcapE: &endcapE
  evt_cuts: 
    - "Keep all evts"
  obj_cuts: &obj_endcapE
    electrons: 
      - "1.479 < |eta| < 2.4"